---
- name: Ensure Apache is installed
  package:
    name: httpd
    state: present

- name: Change SuiteCRM ownership
  file: path={{ suitecrm_install_dir }}/html/suitecrm recurse=yes owner=apache group=apache

- name: Ensure Apache is always running
  service:
    name: httpd
    state: started
    enabled: yes

