---
- name: "Installing repository rpm"
  yum:
    pkg: "{{ item }}" 
    state: present
  with_items:
    - "{{ percona_Repository }}"

- name: "Ensure MySQL packages are installed"
  yum: 
     name: "{{ item }}" 
     state: installed
     enablerepo: "{{ mysql_enablerepo }}"
  with_items: 
    - "{{ mysql_packages }}"
  register: rh_mysql_install_packages

#- name: Install the Python MySQLB module
#  pip: 
#    name: MySQL-python

- name: "Start Myql and enabled"
  service: 
    name: "{{ mysql_service }}"
    state: "{{ mysql_service_state }}"
    enabled: "{{ mysql_service_enabled }}"

- name: "Create 'suitecrm' database"
  mysql_db: 
    name: suitecrm 
    state: present
