---
- name: Install dependencies
  yum: pkg={{ item }} state=present
  with_items:
    - unzip
    - php
    - php-gd
    - php-mysql
    - php-mbstring
    - php-xml
    - php-imap

- name: Configure PHP timezone
  lineinfile: dest=/etc/php.ini regexp='^;date.timezone =$' line='date.timezone = {{ suitecrm_timezone }}' backup=yes
  notify:
  - restart httpd

- name: Configure PHP file upload_max_filesize
  lineinfile: dest=/etc/php.ini regexp='^upload_max_filesize = .*$' line='upload_max_filesize = 30M' backup=yes
  notify:
  - restart httpd

- name: Configure PHP max_execution_time
  lineinfile: dest=/etc/php.ini regexp='^max_execution_time = .*$' line='max_execution_time = 300' backup=yes
  notify:
  - restart httpd

- name: Configure PHP memory_limit
  lineinfile: dest=/etc/php.ini regexp='^memory_limit = .*$' line='memory_limit = 512M' backup=yes
  notify:
  - restart httpd

- name: Configure PHP post_max_size
  lineinfile: dest=/etc/php.ini regexp='^post_max_size = .*$' line='post_max_size = 30M' backup=yes
  notify:
  - restart httpd

- name: Create installation directory
  file: path={{ suitecrm_install_dir }} state=directory

- name: Copy SuiteCRM zipfile
  copy: src='SuiteCRM-{{ suitecrm_version }}.zip' dest={{ suitecrm_install_dir }}

- name: Unzip SuiteCRM
  command: unzip -o 'SuiteCRM-{{ suitecrm_version }}.zip'
  args:
    chdir: "{{ suitecrm_install_dir }}"
    creates: "{{ suitecrm_install_dir }}/suitecrm"

- name: Move SuiteCRM to www directory 
  command: mv /var/www/SuiteCRM-{{ suitecrm_version }} /var/www/html/suitecrm
